import { getShowCoordinates, calculateHaversineDistance } from "../../utils/geoUtils";
const concertBg = "https://cyjnpuneruonskfzpmqo.supabase.co/storage/v1/object/public/public-assets/High%20energy%20concert%202.png";
import React from "react";
import { 
  Sparkles, ChevronRight, Lock, Unlock, Users, Building, HelpCircle, FileText, CheckCircle, Ticket, MapPin, 
  Play, Clock, Star, Edit2, AlertTriangle, Disc, Calendar, Plus, Globe, ShoppingCart, MessageSquare, Bell, Settings,
  Copy, Download, UserPlus, Flame, Check, Radio
, Shield, WifiOff, Wifi, Table, CloudSun, Wind, Sun, Compass, Cloud, CloudRain, CloudSnow, CloudLightning, RefreshCw, Truck, ExternalLink, ChevronDown, X, Coffee, ListTodo, CheckSquare, Square, Plane, User, BarChart2, Printer} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { AnimatedText, AnimatedCount } from "../AnimatedElements";
import { LiveTeamActivityCard } from "./LiveTeamActivityCard";
import { CashDrawerLedgerCard } from "./CashDrawerLedgerCard";
import { DecoupledFinanceCards } from "./DecoupledFinanceCards";
import { MetricsSplitCard, FourCardAutoCarousel, TourNotesCard, BlackBookCard } from "./cards";

const GENRE_REACTION_MATRICES = {
  hardcore: ["🔥", "🔨", "😤", "💪"],
  metalcore: ["💀", "🔪", "🖤", "🩸"],
  pop_punk: ["🍕", "🛹", "🎸", "✨"],
  deathcore: ["😈", "🦇", "🥩", "☠️"],
  default: ["👍", "🔥", "🤘", "💯"]
};

export function HomeDashboardView(props: any & { renderBlackBookCard?: any; renderTourNotesCard?: any; renderFourCardAutoCarousel?: any; renderMetricsSplitCard?: any; renderRecentSalesFeed?: any; }) {
  const {
    userProfile,
    setUserProfile,
    activeClearanceLevel,
    setActiveClearanceLevel,
    simulatedMemberId,
    setSimulatedMemberId,
    isPttRecording,
    setIsPttRecording,
    isInitialHydrated,
    setIsInitialHydrated,
    isNoteExpanded,
    setIsNoteExpanded,
    inlineNoteEditingId,
    setInlineNoteEditingId,
    inlineNoteText,
    setInlineNoteText,
    inlineNoteCategory,
    setInlineNoteCategory,
    inlineNoteTag,
    setInlineNoteTag,
    activeNoteIndex,
    setActiveNoteIndex,
    isTourNotesCardCollapsed,
    setIsTourNotesCardCollapsed,
    currentCoords,
    setCurrentCoords,
    busCallTime,
    setBusCallTime,
    lockupTime,
    setLockupTime,
    isTime24Hour,
    setIsTime24Hour,
    isEditingBusCall,
    setIsEditingBusCall,
    isWeatherForecastExpanded,
    setIsWeatherForecastExpanded,
    customNavDestination,
    setCustomNavDestination,
    isWaypointsExpanded,
    setIsWaypointsExpanded,
    isInteractiveMapExpanded,
    setIsInteractiveMapExpanded,
    isFuelCalculatorExpanded,
    setIsFuelCalculatorExpanded,
    isPreDriveChecklistExpanded,
    setIsPreDriveChecklistExpanded,
    isDriverRotationExpanded,
    setIsDriverRotationExpanded,
    vehicleType,
    setVehicleType,
    fuelPrice,
    setFuelPrice,
    customMpg,
    setCustomMpg,
    activeDriver,
    setActiveDriver,
    driveHoursElapsed,
    setDriveHoursElapsed,
    checkedPreDriveItems,
    setCheckedPreDriveItems,
    waypoints,
    setWaypoints,
    newWaypointName,
    setNewWaypointName,
    newWaypointType,
    setNewWaypointType,
    tempBusCallTime,
    setTempBusCallTime,
    tempLockupTime,
    setTempLockupTime,
    isOfflineSimActive,
    setIsOfflineSimActive,
    isSyncBadgeExpanded,
    setIsSyncBadgeExpanded,
    activeTab,
    setActiveTab,
    distroDeckSubTab,
    setDistroDeckSubTab,
    settingsExpandedSection,
    setSettingsExpandedSection,
    promoHubSubTab,
    setPromoHubSubTab,
    promoHubSelectedItemId,
    setPromoHubSelectedItemId,
    promoCardActiveSlot,
    setPromoCardActiveSlot,
    blackBookCardActiveSlot,
    setBlackBookCardActiveSlot,
    isTransferModalOpen,
    setIsTransferModalOpen,
    isCashDrawerOpen,
    setIsCashDrawerOpen,
    onRouteVenueAddress,
    setOnRouteVenueAddress,
    inlineCashDrawerAddingType,
    setInlineCashDrawerAddingType,
    inlineCashDrawerAmount,
    setInlineCashDrawerAmount,
    inlineCashDrawerDescription,
    setInlineCashDrawerDescription,
    inlineCashDrawerActiveFilter,
    setInlineCashDrawerActiveFilter,
    dashboardV2ActiveNav,
    setDashboardV2ActiveNav,
    isLiveTeamActivityOpen,
    setIsLiveTeamActivityOpen,
    activeEventsSection,
    setActiveEventsSection,
    isV2StoryCreatorExpanded,
    setIsV2StoryCreatorExpanded,
    v2RoleMenuOpen,
    setV2RoleMenuOpen,
    isPttOpen,
    setIsPttOpen,
    allianceActivePostIndex,
    setAllianceActivePostIndex,
    allianceCommentText,
    setAllianceCommentText,
    previewReactionMenuOpenFor,
    setPreviewReactionMenuOpenFor,
    previewFollowedActs,
    setPreviewFollowedActs,
    alliancePosts,
    setAlliancePosts,
    notifications,
    setNotifications,
    isNotificationDrawerOpen,
    setIsNotificationDrawerOpen,
    isNavMenuOpen,
    setIsNavMenuOpen,
    isQuickActionPanelOpen,
    setIsQuickActionPanelOpen,
    pendingOpenShowsForm,
    setPendingOpenShowsForm,
    pendingFlightIsAdding,
    setPendingFlightIsAdding,
    autoExpandShowId,
    setAutoExpandShowId,
    transferPreselectedId,
    setTransferPreselectedId,
    autoOpenSettlementShowId,
    setAutoOpenSettlementShowId,
    isLoggedOut,
    setIsLoggedOut,
    showSplash,
    setShowSplash,
    loginInitialTab,
    setLoginInitialTab,
    isUpgradeMode,
    setIsUpgradeMode,
    showWorkspaceRegistration,
    setShowWorkspaceRegistration,
    currentTime,
    setCurrentTime,
    activePlan,
    setActivePlan,
    isLongPressTriggered,
    setIsLongPressTriggered,
    profileCarouselIndex,
    setProfileCarouselIndex,
    dbStatus,
    setDbStatus,
    isOnline,
    setIsOnline,
    pendingSyncCount,
    setPendingSyncCount,
    logs,
    setLogs,
    isModalOpen,
    setIsModalOpen,
    modalType,
    setModalType,
    selectedSaleReceipt,
    setSelectedSaleReceipt,
    sales,
    setSales,
    shows,
    setShows,
    isHydrated,
    setIsHydrated,
    notes,
    setNotes,
    dailySalesGoal,
    setDailySalesGoal,
    cashTransactions,
    setCashTransactions,
    expenses,
    setExpenses,
    venues,
    setVenues,
    isBandModalOpen,
    setIsBandModalOpen,
    newBandForm,
    setNewBandForm,
    customLogoPreset,
    setCustomLogoPreset,
    editName,
    setEditName,
    editGenre,
    setEditGenre,
    editLogoUrl,
    setEditLogoUrl,
    editLogoPresetIdx,
    setEditLogoPresetIdx,
    dragActive,
    setDragActive,
    bandInfoName,
    setBandInfoName,
    bandInfoHomebase,
    setBandInfoHomebase,
    bandInfoFoundedYear,
    setBandInfoFoundedYear,
    bandInfoBio,
    setBandInfoBio,
    bandInfoCustomSlug,
    setBandInfoCustomSlug,
    bandInfoBookingEmail,
    setBandInfoBookingEmail,
    bandInfoBookingPhone,
    setBandInfoBookingPhone,
    bandInfoYoutubeVideo,
    setBandInfoYoutubeVideo,
    bandInfoStreamingUrl,
    setBandInfoStreamingUrl,
    bandInfoTechRider,
    setBandInfoTechRider,
    bandInfoTourVehicle,
    setBandInfoTourVehicle,
    bandInfoMetalArchivesUrl,
    setBandInfoMetalArchivesUrl,
    logoUploaderDragActive,
    setLogoUploaderDragActive,
    coverUploaderDragActive,
    setCoverUploaderDragActive,
    reviewScore,
    setReviewScore,
    reviewText,
    setReviewText,
    reviewerName,
    setReviewerName,
    reviewerGroup,
    setReviewerGroup,
    reviewLeft,
    setReviewLeft,
    userReviews,
    setUserReviews,
    loyaltyMembers,
    setLoyaltyMembers,
    showNotification,
    setShowNotification,
    leftCarouselIndex,
    setLeftCarouselIndex,
    isLeftCardPaused,
    setIsLeftCardPaused,
    isMetricCarouselPaused,
    setIsMetricCarouselPaused,
    isGlobalHoverPaused,
    setIsGlobalHoverPaused = () => {},
    isEditingSalesGoal,
    setIsEditingSalesGoal,
    salesGoalInput,
    setSalesGoalInput,
    newExpenseDesc,
    setNewExpenseDesc,
    newExpenseAmount,
    setNewExpenseAmount,
    currentMetricIndex,
    setCurrentMetricIndex,
    teamCarouselIndex,
    setTeamCarouselIndex,
    isTeamCarouselPaused,
    setIsTeamCarouselPaused,
    dashboardCarouselIndex,
    setDashboardCarouselIndex,
    selectedGuestlistShowId,
    setSelectedGuestlistShowId,
    localWeather,
    setLocalWeather,
    weatherLoading,
    setWeatherLoading,
    weatherError,
    setWeatherError,
    musicTrackCount,
    setMusicTrackCount,
    revenueSplits,
    setRevenueSplits,
    tourStatusIndex,
    setTourStatusIndex,
    isTourStatusPaused,
    setIsTourStatusPaused,
    isHoveringTourStatus,
    setIsHoveringTourStatus,
    lastInteractionTime,
    setLastInteractionTime,
    isChecklistModalOpen,
    setIsChecklistModalOpen,
    isFlightModalOpen,
    setIsFlightModalOpen,
    flights,
    setFlights,
    checklistItems,
    setChecklistItems,
    checklistBank,
    setChecklistBank,
    bands,
    setBands,
    activeBandId,
    setActiveBandId,
    currentLoadedBandId,
    setCurrentLoadedBandId,
    editingBand,
    setEditingBand,
    deletingBandId,
    setDeletingBandId,
    bandLineup,
    setBandLineup,
    crewMembers,
    setCrewMembers,
    bandLogoUrl,
    setBandLogoUrl,
    bandCoverUrl,
    setBandCoverUrl,
    selectedMicroGenres,
    setSelectedMicroGenres,
    bandJoinRequests,
    setBandJoinRequests,
    inventory,
    setInventory,
    editingItem,
    setEditingItem,
    stagedDistroItems,
    setStagedDistroItems,
    inventoryAudits,
    setInventoryAudits,
    offers,
    setOffers,
    blockedPromoters,
    setBlockedPromoters,
    queueLength,
    isSyncing,
    type,
    operation,
    payload,
    error,
    data,
    count,
    latitude,
    longitude,
    saved,
    handleUnhandledRejection,
    activeBandIdRef,
    userProfileRef,
    NOTE_CATEGORIES,
    NOTE_STATUSES,
    handleNoteTouchStart,
    handleNoteTouchMove,
    handleNoteTouchEnd,
    isRosterOwner,
    isTabRestricted,
    allowed,
    isSubNavRestricted,
    parsed,
    dashboardScrollPos,
    dashboardRef,
    cached,
    defaultAnnouncements,
    handleAlliancePostReaction,
    updated,
    newActive,
    hypeReact,
    matrix,
    emoji,
    label,
    seenIds,
    seenMessages,
    msgKey,
    notifTime,
    prevTime,
    params,
    handleLocationChange,
    handleProfileUpdate,
    handleNavigate,
    playPttSound,
    AudioCtx,
    ctx,
    osc1,
    osc2,
    gain,
    osc,
    bufferSize,
    buffer,
    noise,
    filter,
    renderTime,
    parts,
    min,
    ampm,
    now,
    getTrialCountdownStr,
    isPromoGated,
    yearInMs,
    endTime,
    timeLeft,
    days,
    hours,
    trialDurationMs,
    minutes,
    seconds,
    newSalePressTimer,
    handleNewSalePointerDown,
    handleNewSalePointerUp,
    handleNewSaleClick,
    interval,
    getNextShow,
    todayStr,
    upcoming,
    sorted,
    getSetlistDetailsForShow,
    setlistsMap,
    sl,
    totalSecs,
    timer,
    isSupabaseConfigured,
    handleQueueChanged,
    addLog,
    queueOfflineAction,
    existingQueueStr,
    queue,
    hydrateStores,
    inv,
    pos,
    old,
    shws,
    flts,
    revs,
    vens,
    oldV,
    offs,
    oldO,
    exps,
    oldE,
    lm,
    ct,
    bp,
    existing,
    extendedMap,
    extra,
    isLoadedFromDbRef,
    mockIds,
    activeBand,
    handleCreateOffer,
    handleUpdateOffer,
    nextShows,
    handleAcceptOffer,
    handleDeclineOffer,
    handleBlockPromoter,
    targetOffer,
    promoterId,
    handleRenegotiateOffer,
    supabase,
    validBands,
    cleanBandPayload,
    errors,
    loadCaches,
    legacyBands,
    adminBands,
    adminActiveId,
    userBandsData,
    userActiveId,
    suffix,
    cachedSalesStr,
    cachedShowsStr,
    cachedNotesStr,
    cachedAuditsStr,
    cachedInventoryStr,
    cachedExpensesStr,
    cachedCashTransactionsStr,
    cachedSalesGoalStr,
    defaultExpenses,
    variantsCache,
    bandId,
    savedLineup,
    rawLineup,
    savedCover,
    savedCrew,
    activeSimulatedMember,
    list,
    crewList,
    combined,
    found,
    lvl,
    filteredShows,
    filteredSales,
    filteredInventory,
    filteredNotes,
    logoPresets,
    rosterFileInputRef,
    editRosterFileInputRef,
    bandInfoLogoFileInputRef,
    bandInfoCoverFileInputRef,
    parsedGenres,
    handleBandInfoLogoUpload,
    reader,
    dataUrl,
    userProfileId,
    publicUrl,
    handleBandInfoCoverUpload,
    compressLogoImage,
    img,
    canvas,
    compressedUrl,
    handleLogoUpload,
    handleUpdateBand,
    updatedLogo,
    handleDeleteBand,
    remaining,
    handleCreateBand,
    currentLimit,
    newId,
    bandLogo,
    existingBandsStr,
    existingBands,
    updatedBands,
    registered,
    updatedProfile,
    handleOpenMyProfile,
    isBandWorkspace,
    detailPayload,
    raw,
    triggerNotification,
    handleOfflineSyncSuccess,
    handleRestock,
    saveShowExtraMetadata,
    syncOfflineQueue,
    queueStr,
    dbSale,
    columns,
    dbNote,
    handleOnline,
    handleOffline,
    commitInventoryMutation,
    mutations,
    existsIndex,
    commitSaleMutation,
    validMutations,
    amt,
    qty,
    commitFlightMutation,
    commitShowMutation,
    commitReviewMutation,
    processingGlobalSyncQueue,
    processQueueForModule,
    masterCache,
    localTs,
    cloudTs,
    matchedSplit,
    grossFunds,
    labelLine,
    artistLine,
    cleanPayload,
    setlistsCache,
    handleDataSubmit,
    id,
    timestamp,
    isUpdate,
    handleDeleteNote,
    handleUpdateNote,
    dbUpdates,
    handleMarkNotificationAsRead,
    hydrateModuleData,
    mockSaleIds,
    realSales,
    mockShowIds,
    realShows,
    mockNoteIds,
    realNotes,
    localNotes,
    cvStr,
    formatted,
    cachedStr,
    dbIdSet,
    localOnlyItems,
    merged,
    localAudits,
    localLoyalty,
    localBjr,
    cleanNotifs,
    localNotif,
    unsubscribeSales,
    payloadTime,
    isRecentDuplicate,
    checkTime,
    unsubscribeShows,
    unsubscribeNotes,
    isFallback,
    unsubscribeFlights,
    unsubscribeReviews,
    unsubscribeAudits,
    unsubscribeLoyalty,
    leftTouchStartXRef,
    leftTouchEndXRef,
    leftTouchTimerRef,
    handleLeftTouchStart,
    handleLeftTouchMove,
    handleLeftTouchEnd,
    diffX,
    activeEl,
    isEditing,
    todayStrValForSales,
    todaySalesOnly,
    todayRevenue,
    isCritical,
    totalTableStock,
    totalVanStock,
    dailyExpensesTotal,
    todayStrVal,
    runningExpensesTotal,
    expensePerShow,
    showsCount,
    topSellingItems,
    sortedList,
    mapped,
    dbMatch,
    activeNames,
    fallbackPool,
    sortedShows,
    oneYearFromNow,
    oneYearFromNowStr,
    currentOrNextShow,
    showsNeedingSettlement,
    timeParts,
    h,
    m,
    endThreshold,
    hasSettleReminder,
    firstShowToSettle,
    activeShowDisplay,
    countdownString,
    targetDate,
    diffMs,
    endWindow,
    showSpecificNotes,
    tableStockPercent,
    maxPotential,
    totalSalesCount,
    todaySalesCount,
    todayItemsSold,
    tourTotalRevenue,
    averageSaleValue,
    itemCounts,
    handleAddExpense,
    newExp,
    handleSaveSalesGoal,
    fetchLocalWeather,
    geoRes,
    geoData,
    city,
    subdivision,
    weatherRes,
    weatherData,
    current,
    tempVal,
    relativeHumidity,
    windSpeed,
    code,
    fCode,
    dateObj,
    dayName,
    registerTourStatusInteraction,
    touchStartXRef,
    touchEndXRef,
    handleStatusTouchStart,
    handleStatusTouchMove,
    handleStatusTouchEnd,
    msSinceLastInteraction,
    toggleChecklistItem,
    nextState,
    status,
    teamMembers,
    savedTeam,
    avatars,
    teamActivities,
    member,
    timeMs,
    timeAgo,
    m0,
    m1,
    m2,
    totalInventoryValue,
    metrics,
    renderLegacyMetricsCarousel,
    reactions,
    i,
    hr,
    cachedBands,
    cachedActiveBandIdStr,
    currentActiveBandId,
    width,
    height,
    successCount,
    needsUpdate,
    item,
    skipTableUpsert,
    hasSplitAction,
    sls,
    slsNeedsUpdate,
    active,
    mergedShows,
    targetHour,
    targetMinute,
    topSellerName,
    maxCount,
    cityNameStr,
    conditionStr,
    fIcon,
    avatar,
    App
  } = props;
  
  const { 
    renderBlackBookCard, 
    renderTourNotesCard, 
    renderFourCardAutoCarousel, 
    renderMetricsSplitCard, 
    renderRecentSalesFeed 
  } = props;
  
  return (
          <div 
            className="flex-grow overflow-y-auto pb-4 scrollbar-thin"
            ref={dashboardRef}
            onScroll={(e) => { dashboardScrollPos.current = e.currentTarget.scrollTop; }}
          >
            

            {musicTrackCount === 0 && isRosterOwner && (
              <div className="mx-5 mt-4">
                <button
                  type="button"
                  onClick={() => {
                    setActiveTab('distro-deck');
                    setDistroDeckSubTab('music');
                    triggerNotification?.("Directing to Audio Studio Upload System...");
                  }}
                  className="w-full bg-zinc-950 border border-zinc-800 hover:border-rose-500 hover:bg-rose-500/10 p-4 rounded-xl shadow-[0_0_15px_rgba(244,63,94,0.1)] transition-all duration-300 flex items-center justify-between group cursor-pointer text-left"
                >
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-rose-500/20 rounded-lg group-hover:bg-rose-500/30 transition-colors shrink-0">
                      <Radio className="w-5 h-5 text-rose-500" />
                    </div>
                    <div>
                      <h4 className="text-[11px] font-mono font-black text-rose-500 uppercase tracking-widest block group-hover:text-rose-400">
                        [ ▰ MUSIC TRACKS MISSING // UPLOAD YOUR AUDIO CATALOG ]
                      </h4>
                      <p className="text-[8.5px] font-mono text-zinc-500 leading-snug mt-1 group-hover:text-zinc-400">
                        Zero tracks detected in current profile layer. Complete audio deployments to activate streaming.
                      </p>
                    </div>
                  </div>
                  <ChevronRight className="w-4 h-4 text-zinc-600 group-hover:text-rose-500 transition-colors shrink-0" />
                </button>              </div>
            )}

            
            {/* ACTIVE TOUR BAND BLOCK */}
            <div className="px-5 pt-4 pb-2">
              <div className="flex items-center justify-between gap-2 overflow-hidden">
                <h1 
                  style={{ fontSize: '26px', lineHeight: '28px', fontStyle: 'normal', textDecorationLine: 'none' }}
                  className="font-display font-bold tracking-tight text-white truncate"
                >
                  {activeBand?.name}
                </h1>
                
                <div className="flex items-center gap-1.5 shrink-0 relative">
                  <AnimatePresence>
                    {props.isSyncBadgeExpanded && (
                      <motion.button
                        type="button"
                        initial={{ opacity: 1, x: 20, width: 0 }}
                        animate={{ opacity: 1, x: 0, width: 'auto' }}
                        exit={{ opacity: 1, x: 20, width: 0 }}
                        onClick={() => {
                          props.setIsOfflineSimActive?.((prev: boolean) => {
                            const next = !prev;
                            if (next) {
                              props.triggerNotification?.('⚠️ Local Buffer Mode Active. Simulated network disconnect.');
                              props.addLog?.('Switched to simulated local offline cache buffer.');
                            } else {
                              props.triggerNotification?.('🟢 Back Online. Cloud databases fully synchronized!');
                              props.addLog?.('Switched to simulated cloud synced mode.');
                            }
                            return next;
                          });
                        }}
                        className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl border text-[8.5px] font-bold uppercase tracking-wider font-mono mr-1 shrink-0 ${
                          (props.isOfflineSimActive || !props.isOnline)
                            ? 'bg-amber-950/40 border-amber-900 text-amber-500 hover:bg-amber-950/60 animate-pulse'
                            : 'bg-[#0a3a2e]/40 border-emerald-900 text-emerald-400 hover:bg-[#0a3a2e]/60'
                        }`}
                        title="Click to toggle offline mode simulation"
                      >
                        <span className="w-1.5 h-1.5 rounded-full animate-pulse bg-current" />
                        <span>{(props.isOfflineSimActive || !props.isOnline) ? "SIMULATE OFFLINE" : "LIVE CLOUD SYNC"}</span>
                      </motion.button>
                    )}
                  </AnimatePresence>

                  <button
                    type="button"
                    onClick={() => props.setIsSyncBadgeExpanded?.((p: boolean) => !p)}
                    className={`w-8 h-8 rounded-full border flex items-center justify-center transition-all duration-150 cursor-pointer select-none shrink-0 ${
                      (props.isOfflineSimActive || !props.isOnline)
                        ? 'bg-amber-950/40 border-amber-900 text-amber-500 hover:bg-amber-950/60'
                        : 'bg-[#0a3a2e]/40 border-emerald-950 text-emerald-400 hover:bg-[#0a3a2e]/60'
                    }`}
                    title="Toggle connection status details"
                  >
                    {(props.isOfflineSimActive || !props.isOnline) ? (
                      <WifiOff className="w-4 h-4 text-amber-500 animate-pulse shrink-0" />
                    ) : (
                      <Wifi className="w-4 h-4 text-emerald-400 shrink-0" />
                    )}
                  </button>
                </div>
              </div>
            </div>

            {/* BLACK BOOK TOUR ROUTING CARD */}
            {renderBlackBookCard ? renderBlackBookCard() : <BlackBookCard {...props} />}

            {/* TOUR NOTES CAROUSEL BOX */}
            {renderTourNotesCard ? renderTourNotesCard() : <TourNotesCard {...props} />}

            {renderRecentSalesFeed()}
            {/* RECENT ACTIVITY TICKER */}
            {sales.length > 0 && (
              <div className="px-5 py-2">
                <div className="bg-purple-900/10 border border-purple-500/30 rounded-xl p-3 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="flex h-2 w-2 rounded-full bg-purple-400 animate-pulse" />
                    <span className="text-[10px] font-mono uppercase text-purple-400 font-bold">RECENT ACTIVITY</span>
                  </div>
                  <div className="text-right font-mono text-[10px] text-purple-200 truncate max-w-[200px]">
                    {sales[0].item_name} sold for ${sales[0].amount} ({sales[0].payment_method})
                  </div>
                </div>
              </div>
            )}

          </div>

  );
}
